version: "3"
services:
  web:
    container_name: "web_fastapi_seed-docker"
    build: .
    volumes:
      - ./src/:/dev-code
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Tokyo
